# Generated by Django 2.2.9 on 2020-04-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chunks', '0002_chunk_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('direct', 'Direct'), ('table_fill', 'Table Fill')], max_length=50)),
                ('answer', models.CharField(max_length=200)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chunks.Chunk')),
            ],
        ),
    ]
