# Generated by Django 2.2.9 on 2020-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='instruction',
        ),
        migrations.AddField(
            model_name='question',
            name='instruction_type',
            field=models.CharField(blank=True, choices=[('translate', 'Translate the following'), ('conjugate', 'Conjugate the followiing')], max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='specificInstruction',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
