# Generated by Django 2.2.9 on 2020-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200430_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instruction_type',
            field=models.CharField(blank=True, choices=[('translate', 'Translate the following'), ('conjugate', 'Conjugate the followiing'), ('fill', 'Fill in the blanks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('table_fill', 'Table Fill'), ('multi_choice_fill', 'Multiple Choice Fill')], max_length=50),
        ),
    ]
