# Generated by Django 2.2.9 on 2020-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200511_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('table_fill', 'Table Fill'), ('multiple_choice', 'Multiple Choice')], max_length=50),
        ),
    ]
