# Generated by Django 2.2.9 on 2020-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200511_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
