# Generated by Django 2.2.9 on 2020-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='specificInstruction',
            new_name='specific_instruction',
        ),
    ]
