# Generated by Django 2.2.9 on 2020-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='getting_started',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
