# Generated by Django 2.2.9 on 2020-04-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0002_chunk_data_type'),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocab',
            name='chapter',
        ),
        migrations.AddField(
            model_name='vocab',
            name='chunk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to='chunks.Chunk'),
            preserve_default=False,
        ),
    ]
