# Generated by Django 2.2.9 on 2020-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20200430_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='vacab_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
