# Generated by Django 2.2.9 on 2020-04-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_vocab_vacab_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='vacab_type',
            new_name='vocab_type',
        ),
    ]
