# Generated by Django 2.2.9 on 2020-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_chapter_external_link'),
        ('chunks', '0004_chunk_order'),
        ('modules', '0002_module_getting_started'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_chapters',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='chapters.Chapter'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_chunks',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='chunks.Chunk'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='users_completed', to='modules.Module'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_chapters',
            field=models.ManyToManyField(blank=True, related_name='users_current', to='chapters.Chapter'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_chunks',
            field=models.ManyToManyField(blank=True, related_name='users_current', to='chunks.Chunk'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_modules',
            field=models.ManyToManyField(blank=True, related_name='users_current', to='modules.Module'),
        ),
    ]
