# Generated by Django 2.2.9 on 2020-05-07 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_chapter_external_link'),
        ('modules', '0002_module_getting_started'),
        ('chunks', '0004_chunk_order'),
        ('jwt_auth', '0002_auto_20200505_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chapters.Chapter')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_chapters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_chunks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed_modules',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_chapters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_chunks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_modules',
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='modules.Module')),
                ('user_progress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='jwt_auth.UserProgress')),
            ],
        ),
        migrations.CreateModel(
            name='ChunkProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('chunk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chunks.Chunk')),
                ('user_chapter_progress_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_progress', to='jwt_auth.ChapterProgress')),
            ],
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='user_module_progress_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='jwt_auth.ModuleProgress'),
        ),
    ]
