# Generated by Django 2.2.9 on 2020-05-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200507_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL),
        ),
    ]
