# Generated by Django 2.2.9 on 2020-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_chapterprogress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
