# Generated by Django 2.2.9 on 2020-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20200508_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
