# Generated by Django 2.2.9 on 2020-04-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='chapter',
        ),
        migrations.AddField(
            model_name='page',
            name='chunk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chunks.Chunk'),
            preserve_default=False,
        ),
    ]
