# Generated by Django 2.2.9 on 2020-04-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200424_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='chunks.Chunk'),
        ),
    ]
