# Generated by Django 2.2.9 on 2020-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_auto_20200501_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='external_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
