# Generated by Django 2.2.9 on 2020-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='data_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('test', 'Test')], default='lesson', max_length=20),
            preserve_default=False,
        ),
    ]
